import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  Container, Card, Text, CardBody, Image, Stack, Heading, Divider
} from '@chakra-ui/react'

export default function Home(props) {
  const {response} = props;
  console.log(response)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {response.map(article => {
          return (
            <Container maxW='container.sm' key={article.id}>
    <Card maxW='sm'>
  <CardBody>
    <Image
      src={article.imageUrl}
      alt='Green double couch with wooden legs'
      borderRadius='lg'
      height={200}
      priority
    />
    <Stack mt='6' spacing='3'>
      <Heading size='md'>{article.title}</Heading>
      <Text>
        {article.summary}
      </Text>
      <Text color='blue.600' fontSize='2xl'>
        $450
      </Text>
    </Stack>
  </CardBody>
  <Divider />
</Card>
  </Container>
          )
        })}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const request = await fetch('https://api.spaceflightnewsapi.net/v3/articles')
  const response = await request.json()
  return {
    props: {
      response,
    }
  }
}
